### ISSUE TITLE
Examples pls

### ISSUE THREAD

**Issue by will702** [Guhan-SenSam/Android-Notification-in-Python#1]
Hello Mr. Can U make a simple example for an action button to interact with the python function in that java class .thanks in advance

**Comment by VICTORVICKIE** [comment]
Yes the demos could help people to understand the working so it would be great if a compiled apk is attached with the code @Guhan-SenSam

**Comment by Guhan-SenSam** [comment]
Ya sure...I'll add the examples in few hours

**Comment by will702** [comment]
thank you for responding
